### ISSUE TITLE
Bounty 5 - Create information page and index page with view more button

### ISSUE THREAD

**Issue by vaibhavgeek** [Kleo-Network/extension#7]
1. The information page UI must be similar to the popup and display all the information data that has been communicated to the website. (In a disabled state as it is, and if successfully shared  true with the organisation then a green tick, if successfully shared falsely then a red tick) ✅  
2. One accordian should always be open. ✅  
3. Update window size (increase size) and remove text / title from the main window popup. 
4. Add view more button in button.
5. When even one is selected it should toggle to yes. ✅
6. Fix state update for browser history tier 1 and tier 2. -- frontend ✅

These updates separately discussed in more detail in the call as well.

**Comment by baibhavKumar1** [comment]
Hey @vaibhavgeek , Is this open? Thank You

**Comment by vaibhavgeek** [comment]
@Wholesomebruh can you reach out to me on discord? Let's discuss.

**Comment by baibhavKumar1** [comment]
Searched everywhere, still can't find way to connect on discord. Any help?

**Comment by vaibhavgeek** [comment]
https://discord.gg/Qn6ZmecTEw @Wholesomebruh
